### ISSUE TITLE
get rid of openMP R CMD check issue

### ISSUE THREAD

**Issue by maxheld83** [maxheld83/pensieve#192]
not a big deal, but still annoying

**Comment by maxheld83** [comment]
depends on this external issue: https://github.com/Rdatatable/data.table/issues/1939

**Comment by maxheld83** [comment]
`data.table`, which causes the problem here (has openMP dep) could also be avoided as a dep completely, by hard-saving the `randomNames` pkg as per #163

**Comment by mattdowle** [comment]
You didn't include what the issue is.  There is this which is now fixed and about to go to CRAN.  Is that what you're referring to?

> It seems OpenMP is not available on CRAN's Mac platform; NOTEs have appeared in CRAN checks. Moved Rprintf from init.c to packageStartupMessage to avoid the NOTE as requested urgently by Professor Ripley. Also fixed the bad grammar of the message: 'single threaded' now 'single-threaded'. If you have a Mac and run macOS or OS X on it (I run Ubuntu on mine) please contact CRAN maintainers and/or Apple if you'd like CRAN's Mac binary to support OpenMP. Otherwise, please follow these instructions for OpenMP on Mac which people have reported success with.

data.table does not have a dependency on OpenMP.  Where did you get that idea from?  If OpenMP isn't available (as on CRAN's Mac) then it will still compile, run and pass all tests.

**Comment by maxheld83** [comment]
thank so much @mattdowle; issue is over at https://github.com/Rdatatable/data.table/issues/1939

Sorry for causing extra confusion here; this issue here is just a note-to-self in my own pkg dev.

And yes, I spoke loosely when talking about the `OpenMP` dep; I meant the NOTE.

Anyway, I'd really *like* to use `OpenMP` as a backend to `data.table` at some point on the Mac.

**Comment by maxheld83** [comment]
problem solved locally on OS X as per above issue; issue will remain on Travis etc though until #163 is done.
